spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
    # TODO посмотреть подробно что это
    open-in-view: true
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    #show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: "UTC+03:00"