spring:
  datasource:
    # TODO add ssl
    url: "jdbc:mysql://192.168.170.135:3306/vk_tests?useSSL=false"
    username: "vk_tests"
    password: "vk_tests"
  jpa:
    hibernate:
      # TODO поменять на validate после тестов
      ddl-auto: create
      use-new-id-generator-mappings: true
    # TODO посмотреть подробно что это
    open-in-view: true
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"